<?php
/**
 * @file
 * Drupal Module: csupport
 * Adds an inline live chat button powered by cSupport
 * to the bottom of all your Drupal pages
 */

/**
 * Implementation of hook_help().
 */
function csupport_help($path, $arg) {
  switch ($path) {
    case 'admin/config/system/csupport':
      return t('This module implements an inline Live Chat button powered by cSupport. Need help? Check our <a href="@url" target="_blank">knowledge base</a>.', array('@url' => 'https://csupporthq.com/knowledge-base/'));
  }
}

/**
 * Implementation of hook_menu().
 */
function csupport_menu() {
  $items['admin/config/system/csupport'] = array(
    'title' => 'cSupport Live Chat',
    'description' => 'Configure the settings used to generate your cSupport code.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('csupport_admin_settings_form'),
    'access arguments' => array('administer csupport'),
    'file' => 'csupport.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implementation of hook_permission().
 */
function csupport_permission() {
  return array(
    'administer csupport' => array(
      'title' => t('Administer cSupport Live Chat module'),
      'description' => t('Permission to change cSupport Live Chat module settings')
    )
  );
}

/**
 * Implementation of hook_page_alter().
 */
function csupport_page_alter(&$page) {
  global $user;
  $domain = variable_get('csupport_id', '');

  // Verify that there is a valid ID, that the user should see the livechat and the page should include this live chat
  if (!empty($domain) && _csupport_role_can_see($user) && _csupport_page_should_show()) {
    // Loading specific settings
    $type = variable_get('csupport_type', '');
    $autofill = variable_get('csupport_autofill', '');
    $autostart = variable_get('csupport_autostart', '');
    $margin = intVal(variable_get('csupport_margin', ''));
    $position = variable_get('csupport_position', '');
    $bgcolor = variable_get('csupport_bgcolor', '');

    // Building the tag from loaded variables
    $script = '(function() { var src = ("https:" == document.location.protocol ? "https://" : "http://") + "' . $domain . '/external/' . $type . '.js";document.write(\'<script src="\'+src+\'" type="text/javascript"><\/script>\');})();';

    if ($autofill==1) {
      $script .= 'var cs_name="' . ($user->name) . '";var cs_email="' . ($user->mail) . '";';
      if ($autostart==1)
        $script .= 'var cs_autostart=true;';
    }

    if ($margin>0 && $margin<101) $script .= 'var cs_margin="' . $margin . 'px";';
    if ($position=='t-l' || $position=='t-r' || $position=='b-l' || $position=='b-r') $script .= 'var cs_position="' . $position . '";';
    if (preg_match('/^#[a-fA-F0-9]{6}$/i', $bgcolor))
      $script .= 'var cs_bgcolor="' . $bgcolor . '";';

    drupal_add_js($script, array('type' => 'inline', 'scope' => 'footer'));
  }
}

/**
 * Implementation of hook_requirements().
 */
function csupport_requirements($phase) {
  $requirements = array();
  if ($phase == 'runtime') {
    if (variable_get('csupport_id', FALSE) == FALSE) {
      $requirements['csupport'] = array(
        'title' => t('cSupport Live Chat Plugin'),
        'description' => t('The cSupport Live Chat Plugin has not been configured properly yet. Go to  the <a href="@url">cSupport settings page</a> to fix it.', array('@url' => url('admin/config/system/csupport'))),
        'severity' => REQUIREMENT_ERROR,
        'value' => t('Not configured'),
      );
    }
  }
  return $requirements;
}

/**
 * Check if user can see the live chat or not
 */
function _csupport_role_can_see($user) {
  $roles_set = variable_get('csupport_visibility_roles', array());
  foreach ($user->roles as $id => $role) // Loop through the roles of the user
    if (isset($roles_set[$id]) && $roles_set[$id]==$id) return FALSE; // Exclude the live char for this role/user
  return TRUE; // User should see the live chat
}

/**
 * Check if page should show the live chat or not
 */
function _csupport_page_should_show() {
  $pages = variable_get('csupport_visibility_pages', '');
  // Match path if necessary.
  if (drupal_strlen($pages)>0) {
    $visibility_pages_type = variable_get('csupport_visibility_pages_type', 0);
    $found = drupal_match_path(drupal_get_path_alias($_GET['q']), $pages);
    if (!$found && $visibility_pages_type==1) return FALSE; // Page is not in include list
    elseif ($found && $visibility_pages_type==0) return FALSE; // Page is in exclude list
  }
  return TRUE; // Page should include the live chat
}